"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, Camera, ChevronDown, ClipboardList, Mic, Send, Volume2, Square, Sparkles, Info, LoaderCircle } from "lucide-react";
import Image from "next/image";
import { getReadiness } from "@/lib/domain";
import { apiFetch, apiRecord } from "@/lib/client-api";
import type { PetRecord, Message } from "@/lib/types";
import { PetAvatar } from "./ui";

interface SpeechRecognitionLike { lang:string; continuous:boolean; interimResults:boolean; start:()=>void; stop:()=>void; onresult:((event:{results:{[index:number]:{[index:number]:{transcript:string}}}})=>void)|null; onerror:(()=>void)|null; onend:(()=>void)|null }
type SpeechWindow = Window & { SpeechRecognition?:new()=>SpeechRecognitionLike; webkitSpeechRecognition?:new()=>SpeechRecognitionLike };
const modeLabels:Record<string,string> = {gemini:"Gemini · cyfrowy głos",grounded:"Odpowiedź lokalna · zapisane informacje",demo:"Demonstracja · profil w przygotowaniu",health:"Informacja o zdrowiu",ollama:"Model lokalny"};

export function ChatView({record,onUpdate,onTest,onCapture,onSettings}:{record:PetRecord;onUpdate:(record:PetRecord)=>void;onTest:()=>void;onCapture:()=>void;onSettings:()=>void}) {
  const [input,setInput]=useState(""); const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState(""); const [listening,setListening]=useState(false);const [canDictate,setCanDictate]=useState(false);const [canSpeak,setCanSpeak]=useState(false);const [speaking,setSpeaking]=useState<string|null>(null);
  const scrollRef=useRef<HTMLDivElement>(null);const recognition=useRef<SpeechRecognitionLike|null>(null);const current=useRef(record);current.current=record;const ready=getReadiness(record);
  useEffect(()=>{const w=window as SpeechWindow;setCanDictate(Boolean(w.SpeechRecognition||w.webkitSpeechRecognition));setCanSpeak("speechSynthesis" in window);return()=>{recognition.current?.stop();window.speechSynthesis?.cancel();};},[]);
  useEffect(()=>{scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:"smooth"});},[record.messages.length,busy]);
  async function send(text=input) {
    if(busy||!text.trim())return; const prompt=text.trim().slice(0,2000);setInput("");setError("");setNotice("");setBusy(true);recognition.current?.stop();
    const message:Message={id:crypto.randomUUID(),role:"user",content:prompt,createdAt:new Date().toISOString()};const snapshot={...current.current,messages:[...current.current.messages,message]};onUpdate(snapshot);
    try { const result=await apiFetch("/api/chat",{record:apiRecord(snapshot),message:prompt});setNotice(result.notice??"");const reply:Message={id:crypto.randomUUID(),role:"assistant",content:result.content,createdAt:new Date().toISOString(),evidence:result.evidence??[],mode:result.mode,provider:result.provider};onUpdate({...current.current,messages:[...current.current.messages,reply]}); }
    catch(e){setError(e instanceof Error?e.message:"Nie udało się odpowiedzieć. Spróbuj ponownie.");setInput(prompt);}finally{setBusy(false);}
  }
  function dictate(){if(listening){recognition.current?.stop();return;}const w=window as SpeechWindow;const Constructor=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Constructor)return;const r=new Constructor();r.lang="pl-PL";r.continuous=false;r.interimResults=false;r.onresult=e=>setInput(previous=>`${previous} ${e.results[0][0].transcript}`.trim());r.onerror=()=>{setError("Dyktowanie nie jest dostępne. Sprawdź zgodę na mikrofon lub wpisz wiadomość.");setListening(false);};r.onend=()=>setListening(false);recognition.current=r;try{r.start();setListening(true);}catch{setListening(false);}}
  function speak(message:Message){if(speaking===message.id){window.speechSynthesis.cancel();setSpeaking(null);return;}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(message.content);utterance.lang="pl-PL";utterance.rate=.97;utterance.onend=()=>setSpeaking(null);utterance.onerror=()=>setSpeaking(null);setSpeaking(message.id);window.speechSynthesis.speak(utterance);}
  const suggestions=record.pet.species==="cat"?["Jaka zabawa sprawia Ci radość?","Co pomaga Ci czuć się bezpiecznie?","Jak lubisz spędzać ze mną czas?"]:["Co lubisz robić na spacerze?","Co pomaga Ci odpocząć?","Jak lubisz spędzać ze mną czas?"];
  return <div className="chat-view">
    <header className="chat-heading"><div className="chat-identity"><PetAvatar pet={record.pet} large/><div><h1>{record.pet.name}</h1><p>{record.isDemo?"Przykładowa kotka · dane demonstracyjne":ready.ready?"Twój towarzysz rozmowy":"Poznajemy się · profil w przygotowaniu"}</p></div></div><button className="button secondary compact" onClick={onSettings}><Sparkles size={16}/>Gemini i konto</button></header>
    {(!ready.ready||record.isDemo)&&<div className="preparation-strip"><div><Info size={18}/><p>{record.isDemo?"To przykładowa rozmowa z Luną. Dodaj własnego zwierzaka, aby stworzyć jego profil.":`Przed osobistą rozmową: ${ready.answered}/${ready.total} pytań i ${ready.clips}/${ready.totalClips} kontekstów wideo. Teraz pokazujemy oznaczoną demonstrację.`}</p></div>{!record.isDemo&&<div><button onClick={onTest}><ClipboardList size={16}/>Kontynuuj test</button><button onClick={onCapture}><Camera size={16}/>Nagraj reakcje</button></div>}</div>}
    <div className="conversation" ref={scrollRef} aria-live="polite" aria-relevant="additions">
      {record.messages.length===0&&<div className="chat-intro"><div className="intro-art"><Image src={record.pet.species==="cat"?"/images/pet-cat.png":"/images/pet-dog.png"} alt="Ilustracja cyfrowego towarzysza" fill sizes="420px"/></div><h2>Jest tyle, o czym możemy porozmawiać.</h2><p>Zapytaj o codzienne potrzeby, ulubione chwile i to, co widzisz w zachowaniu {record.pet.name}.</p><div className="suggestions">{suggestions.map(s=><button key={s} onClick={()=>send(s)} disabled={busy}>{s}<ArrowRight size={15}/></button>)}</div></div>}
      {record.messages.map(message=><article className={`message ${message.role}`} key={message.id}>{message.role==="assistant"&&<PetAvatar pet={record.pet}/>}<div className="message-body"><span className="message-name">{message.role==="user"?"Ty":record.pet.name}{message.role==="assistant"&&<small>{message.provider==="gemini"&&message.mode==="demo"?"Gemini · demonstracja":modeLabels[message.mode??"grounded"]}</small>}</span><div className="message-content">{message.content}</div>{message.role==="assistant"&&<div className="message-tools">{canSpeak&&<button className="text-button" onClick={()=>speak(message)}>{speaking===message.id?<Square size={14}/>:<Volume2 size={15}/>} {speaking===message.id?"Zatrzymaj":"Posłuchaj"}</button>}{Boolean(message.evidence?.length)&&<details className="message-evidence"><summary>Skąd to wiesz?<ChevronDown size={14}/></summary><div>{message.evidence?.map(item=><section key={item.id}><strong>{item.title}</strong><span className="caption">{item.kind==="owner_report"?"Relacja opiekuna":item.kind==="video"?"Adnotacja nagrania":"Baza wiedzy"}</span><p>{item.excerpt}</p>{item.url&&<a href={item.url} target="_blank" rel="noreferrer">Otwórz źródło ↗</a>}</section>)}</div></details>}</div>}</div></article>)}
      {busy&&<div className="reply-loading" role="status"><LoaderCircle className="spin" size={18}/>Przygotowuję odpowiedź…</div>}
    </div>
    <footer className="chat-footer">{notice&&<p className="provider-notice" role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}<form className="chat-composer" onSubmit={e=>{e.preventDefault();void send();}}>{canDictate&&<button type="button" className={`icon-button ${listening?"recording":""}`} aria-label={listening?"Zatrzymaj dyktowanie":"Podyktuj wiadomość po polsku"} onClick={dictate}><Mic size={23}/></button>}<textarea aria-label={`Wiadomość do ${record.pet.name}`} placeholder={`O co chcesz zapytać ${record.pet.name}?`} value={input} onChange={e=>setInput(e.target.value)} maxLength={2000} rows={1} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}}/><button className="send-orb" type="submit" disabled={busy||!input.trim()} aria-label="Wyślij wiadomość"><Send size={21}/></button></form><p className="chat-disclosure">Cyfrowy głos to wyobrażona wypowiedź oparta na dostępnych informacjach. Możesz sprawdzić podstawę każdej odpowiedzi.</p></footer>
  </div>;
}
