"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, Check, LoaderCircle, ShieldCheck } from "lucide-react";
import { apiFetch } from "@/lib/client-api";
import { getCloudUser } from "@/lib/cloud";
import { getSupabase } from "@/lib/supabase";
import type { PublicPaymentConfig } from "@/lib/payments/contracts";
import styles from "./public-info.module.css";
const money = (cents:number)=>new Intl.NumberFormat("pl-PL",{style:"currency",currency:"PLN"}).format(cents/100);
export function PaymentCheckout(){
  const[config,setConfig]=useState<PublicPaymentConfig|null>(null);const[email,setEmail]=useState<string|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[accepted,setAccepted]=useState(false);const[privacy,setPrivacy]=useState(false);const[immediate,setImmediate]=useState(false);const[adult,setAdult]=useState(false);const[idempotency]=useState(()=>crypto.randomUUID());const submitting=useRef(false);
  useEffect(()=>{let disposed=false;void Promise.all([apiFetch("/api/payments/config"),getCloudUser()]).then(([data,user])=>{if(!disposed){setConfig(data);setEmail(user?.email&&user.email_confirmed_at?user.email:null)}}).catch(()=>{if(!disposed)setError("Nie udało się sprawdzić oferty. Sprzedaż pozostaje niedostępna; odśwież stronę lub napisz do nas.")});return()=>{disposed=true}},[]);
  async function checkout(){if(!config?.enabled||!config.product||!config.offerVersion||submitting.current)return;submitting.current=true;setBusy(true);setError("");try{const client=getSupabase();const session=client?await client.auth.getSession():null;const token=session?.data.session?.access_token;if(!token)throw new Error("Zaloguj się na konto użyte do zamówienia.");const response=await fetch("/api/payments/checkout",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(65000),body:JSON.stringify({productId:config.product.id,offerVersion:config.offerVersion,termsVersion:config.agreements.termsVersion,privacyVersion:config.agreements.privacyVersion,acceptTerms:accepted,acknowledgePrivacy:privacy,requestImmediateService:immediate,confirmAdult:adult,idempotencyKey:idempotency})});const result=await response.json();if(!response.ok&&!result.orderId)throw new Error(result.error||"Nie udało się przygotować zamówienia.");if(result.redirectUrl){const url=new URL(result.redirectUrl);const expected=config.environment==="sandbox"?"sandbox.przelewy24.pl":"secure.przelewy24.pl";if(url.protocol!=="https:"||url.hostname!==expected)throw new Error("Niepoprawny adres operatora płatności. Spróbuj ponownie lub skontaktuj się z nami.");window.location.assign(url.href)}else if(result.orderId){window.location.assign(`/platnosci/wynik?orderId=${encodeURIComponent(result.orderId)}`)}else throw new Error("Operator nie przygotował płatności. Nie otrzymano potwierdzenia zamówienia.")}catch(e){setError(e instanceof Error?e.message:"Nie udało się rozpocząć płatności.");submitting.current=false;setBusy(false)}}
  if(error&&!config)return <p role="alert" className="error">{error}</p>;
  if(!config)return <p className="payment-checking" role="status"><LoaderCircle size={18} className="spin"/>Sprawdzamy dostępność pakietów…</p>;
  if(!config.enabled||!config.product)return <div className="payment-pilot"><span className="eyebrow">Możesz zacząć już teraz</span><h2>Bezpłatny pilotaż</h2><p>Twórz profil, przejdź test, zapisuj filmy i własne obserwacje. Korzystaj z wiedzy oraz oznaczonej odpowiedzi lokalnej.</p><ul><li>85 pytań w 11 obszarach dla psa lub kota</li><li>Cztery spokojne konteksty nagrań</li><li>Historia, kopia danych i 290 kart wiedzy</li></ul><p className="payment-state"><ShieldCheck size={17}/>{config.notice||"Sprzedaż płatnych pakietów jest obecnie wyłączona."}</p><p>Publiczne generowanie przez Gemini nie jest obecnie uruchomione. Dodanie profilu nie tworzy płatnego zamówienia.</p><Link className={styles.primaryLink} href="/">Otwórz aplikację<ArrowRight size={18}/></Link><Link className="payment-help-link" href="/pomoc">Zobacz pierwszy krok</Link></div>;
  const p=config.product;
  return <div className="payment-offer"><span className="eyebrow">{config.environment==="sandbox"?"Środowisko testowe Przelewy24":"Jednorazowy zakup"}</span><h2>{p.title}</h2><p>{p.description}</p><p className="payment-price">{money(p.amountCents)} <small>brutto · jednorazowo</small></p><ul><li>{p.durationDays} dni dostępu od potwierdzenia</li><li>Do {p.maxPets} profili · {p.chatLimit} odpowiedzi · {p.analysisLimit} analiz</li><li>Bez automatycznego odnowienia</li></ul>{config.environment==="sandbox"&&<p className="info-box">To test techniczny bez rzeczywistej opłaty. Nie jest zakupem produkcyjnego dostępu. Limity płatnej usługi nie są jeszcze egzekwowane w pilotażu.</p>}{!email?<p className="info-box">Do zamówienia potrzebne jest potwierdzone konto e-mail. <Link href="/">Wróć do aplikacji i otwórz Ustawienia</Link>. Aktualne ograniczenia rejestracji opisuje <Link href="/pomoc#dostep-do-rozmowy">pomoc</Link>.</p>:<><p>Potwierdzenie dla: <strong>{email}</strong></p><form onSubmit={e=>{e.preventDefault();void checkout()}} className="payment-form"><label className="check-label"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} required/><span>Akceptuję <Link href="/regulamin" target="_blank">regulamin</Link>, wersja {config.agreements.termsVersion}.</span></label><label className="check-label"><input type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)} required/><span>Zapoznałem się z <Link href="/polityka-prywatnosci" target="_blank">polityką prywatności</Link>, wersja {config.agreements.privacyVersion}.</span></label><label className="check-label"><input type="checkbox" checked={immediate} onChange={e=>setImmediate(e.target.checked)} required/><span>Proszę o rozpoczęcie dostępu po potwierdzeniu płatności. Zachowuję pełne 14 dni na odstąpienie i zwrot ceny.</span></label><label className="check-label"><input type="checkbox" checked={adult} onChange={e=>setAdult(e.target.checked)} required/><span>Mam ukończone 18 lat.</span></label><button className={styles.primaryLink} type="submit" disabled={busy||!accepted||!privacy||!immediate||!adult}>{busy?<LoaderCircle size={18} className="spin"/>:<Check size={18}/>} {config.environment==="sandbox"?`Testuję płatność ${money(p.amountCents)}`:`Zamawiam i płacę ${money(p.amountCents)}`}</button></form></>}{error&&<p className="error" role="alert">{error}</p>}<p className="caption">Kwota i warunki są sprawdzane przez serwer. Powrót z bramki nie potwierdza zapłaty. <Link href="/odstapienie">Odstąpienie i reklamacje</Link>.</p></div>;
}
